# Generated by Django 3.0.4 on 2020-03-12 12:45

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('email_id', models.EmailField(max_length=255)),
                ('mobile', phone_field.models.PhoneField(blank=True, help_text='Contact_number', max_length=31)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('available', models.BooleanField()),
                ('genre', models.CharField(choices=[('R', 'Romantic'), ('T', 'Thriller'), ('S', 'Study_Books')], max_length=1)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book_ed.User')),
            ],
        ),
    ]
